### ISSUE TITLE
Authentification with elasticsearch server

### ISSUE THREAD

**Issue by patrickbaber** [DMKEBUSINESSGMBH/typo3-mksearch#1]
First of all thanks for your good work!

Is there a way to use an external TLS encrypted and Basic Auth protected elasticsearch server with this extension? I only find a field with a little bit weird syntax for "index;host,port,path". A definition of an URI with this syntax would be very nice. Thanks!

https://user:password@example.com:123/path/

**Comment by hannesbochmann** [comment]
Sorry for the late response. In the moment this is not possible. mksearch can't pass the headers while instantiating the client like in this example https://gist.github.com/phillro/1147306
The easiest way right now would be to white list the IP of the server requesting the ElasticSearch server.
