### ISSUE TITLE
Compatibility with 7.6

### ISSUE THREAD

**Issue by kersten** [DMKEBUSINESSGMBH/typo3-mksearch#12]
Hi,

I get multiple errors using this extension in 7.6? Did I do something wrong?

Greetings

**Comment by hannesbochmann** [comment]
What errors do you get?

**Comment by kersten** [comment]
If I click on "MK Search" in left navigation
```Warning: require_once(../../../../typo3/init.php): failed to open stream: No such file or directory in /var/www/webroot/typo3conf/ext/mksearch/mod1/index.php on line 32```

If I insert the plugin:

```#1437750231: The way registering a wizard in TCA has changed in 6.2 and was removed in CMS 7. Please set module[name]=module_name instead of using script=path/to/script.php in your TCA.```

**Comment by hannesbochmann** [comment]
Which version of mksearch do you use?

**Comment by kersten** [comment]
```"dmk/mksearch": "^1.5"```

**Comment by hannesbochmann** [comment]
You should use the master version as the adjustments for the compatibility for TYPO3 7.6 are not tagged yet.
