### ISSUE TITLE
enable grouping by default

### ISSUE THREAD

**Issue by hannesbochmann** [DMKEBUSINESSGMBH/typo3-mksearch#18]
At the moment the grouped search in Solr is disabled by default. In many environments this will lead to multiple tt_content search results per page. This is suboptimal for users as they get to the same page through various links. That's why I would like to enable the grouping by default so users will only get one tt_content as search result per page. This should only influence tt_content results.

Any objections?

**Comment by digedag** [comment]
This sounds good to me.

**Comment by rengaw83** [comment]
Where you want do enable the grouping by default? 
In flexform for the Plugins? No problem!
In TypoScript? No, please do not!

You mean lastly, the search becomes with the grouped search noticeably slower. 
Can you supply some values? By which factor the search is slower? With how many docs you have testet?

**Comment by hannesbochmann** [comment]
In flexform as well as in TypoScript. Why don't you want that in TypoScript? You won't even notice the difference except for loosing useless search results.
I did a test search in a pool of ~6000 docs. The query time differed by 3ms. So this won't slow down a search noticeably. The time that Solr takes is by far the smallest part when it comes to do the search in TYPO3. Furthermore I can't find any bad experience in the web except for group.facet. But this is not in use.

**Comment by hannesbochmann** [comment]
By the way, you can check that for yourself easily. Just do a normal search in the admin panel of Solr and add "&group=true&group.field=id&group.ngroups=true&group.truncate=true". That should simulate the same behaviour as mksearch.

**Comment by rengaw83** [comment]
I have done some short tests.

~60k docs, Solr6.2, dismax: 
without grouping ~10ms 
with grouping ~200ms.

~90k docs, Solr4.7,simple select handler:
without grouping ~1ms
with grouping ~2500ms

I assume this feature will be enabled in all the projects with a solr search out there by an update, when you set it in ts by default in mksearch?
So i think we should not enable this by default in ts. 
This feature will be enabled in all searches without indexed content elements (newssearches, etc.), too.

In flexform it is no problem for me. It has no impact on existing projects. But ther should be a note in csh or doc to this eventual performance issue.

**Comment by hannesbochmann** [comment]
Good that someone was that critical. ;-) Maybe the grouping feature needs some tweaking or there is a more performant way. For rather small indexes that's no problem (differences are not really noticeable) but obviously for larger ones.
Nevertheless I enabled it by default in flexform and added a hint.
