### ISSUE TITLE
Problem after installation on 7.6.10

### ISSUE THREAD

**Issue by madaxel** [DMKEBUSINESSGMBH/typo3-mksearch#21]
After installation i get the error that in rn_base/mod/class.tx_rnbase_mod_BaseModule.php on line 34 includeLLFile()  cannot on be called on null Object.

Solution: 
/** @var $GLOBALS['LANG'] \TYPO3\CMS\Lang\LanguageService */
$GLOBALS['LANG'] = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Lang\LanguageService::class);
$GLOBALS['LANG']->init($GLOBALS['BE_USER']->uc['lang']);
$GLOBALS['LANG']->includeLLFile('EXT:rn_base/mod/locallang.xml');

Can someone confirm the problem

**Comment by hannesbochmann** [comment]
This is the wrong place as the problem is in rn_base. Please report the bug [here](https://github.com/digedag/rn_base/issues) and mention also the rn_base version. 
But I think the rn_base version is too old. Can you please try with the newest version from [github](https://github.com/digedag/rn_base).

**Comment by madaxel** [comment]
Thanks for your feedback, 
I had Version 1.0.9 from TER. With 1.1.12 from actual Master it is working. Maybe you need to adjust your dependency settings.
I just ask for a new TER release here https://github.com/digedag/rn_base/issues/77

**Comment by hannesbochmann** [comment]
Dependecies have been adjusted but there wasn't a TER release in a long time. I suggest not to use TER but composer with the package dmk/mksearch or directly github with the latest tag.

**Comment by madaxel** [comment]
TER release will be before christmas as stated in https://github.com/digedag/rn_base/issues/77
Should I use mksearch from git and not from TER?

**Comment by hannesbochmann** [comment]
We do it this way. There is no real advantage in using TER except that you can install extensions through the extension manager. 
We recommend to use composer to build the complete project.
