### ISSUE TITLE
Unable to open BackendModule

### ISSUE THREAD

**Issue by madaxel** [DMKEBUSINESSGMBH/typo3-mksearch#22]
After fixing the previous errror i called the Backendmodule and get 
#1442431631: Object "tx_mksearch_mod1_Module" doesn't implement an __invoke() method and cannot be used as target. (More information)

InvalidArgumentException thrown in file
/home/markus/public_html/typo3_src-7.6.10/typo3/sysext/core/Classes/Http/Dispatcher.php in line 66.

TYPO3 7.6.10
PHP Version: 5.6.29-1+deb.sury.org~xenial+1

**Comment by hannesbochmann** [comment]
The same as Issue #21
