### ISSUE TITLE
Elastic Search status path is deprecated

### ISSUE THREAD

**Issue by dextar1** [DMKEBUSINESSGMBH/typo3-mksearch#26]
_status api is replaced with _stats API 

on this line:
https://github.com/DMKEBUSINESSGMBH/typo3-mksearch/blob/master/lib/Elastica/Status.php#L164

check API https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-stats.html

**Comment by hannesbochmann** [comment]
Thanks, we need to update the Elastica library.

**Comment by hannesbochmann** [comment]
Feel free to provide a pull requets.

**Comment by dextar1** [comment]
i worked on it a bit, didnt update Elastica but changed some code in Elastica and made it work with latest Elastic Search. right now i have to make a solution for one of my projects. maybe after that i will update Elastica in mksearch

**Comment by rengaw83** [comment]
Closing in favour of #29
