### ISSUE TITLE
FE Plugin isnt working

### ISSUE THREAD

**Issue by dextar1** [DMKEBUSINESSGMBH/typo3-mksearch#27]
Hi,
I have clean 7.6 LTS and i installed rn_base and mksearch from TER. I placed FE plugin but nothing shows on FE side.

**Comment by hannesbochmann** [comment]
Have you included the static TypoScript of mksearch?

**Comment by dextar1** [comment]
yes

**Comment by dextar1** [comment]
typoscript of mksearch is also added in include tab

**Comment by hannesbochmann** [comment]
Have you checked error/dev logs?

**Comment by dextar1** [comment]
no error in error log. i am using nginx

**Comment by dextar1** [comment]
i echo something in tx_rnbase_controller->main and still nothing.

**Comment by hannesbochmann** [comment]
Can you check if the class tx_rnbase_controller can be loaded/instantiated?

**Comment by dextar1** [comment]
that class doesn't exist. so that means ext_autoload.php isn't working in TYPO3 7 LTS. But if you are your team tested it in 7.6 LTS? because in this way it would be helpful for me to know that it worked on 7.6 and then i can check my things.

**Comment by hannesbochmann** [comment]
We use those extensions in TYPO3 7.6. Maybe there is an issue with composer. In our projects the autoloading is handled by composer. Maybe there is a bug in the autoloading configuration for TYPO3 without composer (is done through the configuration in ext_emconf.php. ext_autoload.php is deprecated and not used anymore).
Unfortunately I have no free time to take a closer look.

**Comment by dextar1** [comment]
ok thanks for the help, i will check that.
