### ISSUE TITLE
It indexes tt_address or tt_news records but not pages or tt_content records

### ISSUE THREAD

**Issue by dextar1** [DMKEBUSINESSGMBH/typo3-mksearch#28]
It indexes tt_address or tt_news records but not pages or tt_content records

**Comment by hannesbochmann** [comment]
How do you mean that? mksearch is fully capable to index tt_content. The only thing you have to do is to configure an indexer for tt_content in the backend module.

**Comment by dextar1** [comment]
i created an index configuration for core and subtype as tt_content. and then in TS i uncommented page tree part and added my own root page id there. but still in index queue it shows tt_contet 0 records

**Comment by hannesbochmann** [comment]
Did you reset (click checkbox and then trigger indexing) the tt_content table in the backend module?

**Comment by dextar1** [comment]
ah yeah now with reset checkbox, now its working. thanks 👍
