### ISSUE TITLE
If we can add multiple docs for one record?

### ISSUE THREAD

**Issue by dextar1** [DMKEBUSINESSGMBH/typo3-mksearch#31]
Hi,
i have used solr in the past and it provides a hook to add multiple index documents for the same record. like here https://github.com/TYPO3-extensions/solr/blob/master/Classes/Typo3PageIndexer.php#L364-L387

but at this line https://github.com/DMKEBUSINESSGMBH/typo3-mksearch/blob/master/service/internal/class.tx_mksearch_service_internal_Index.php#L454 you get one document for one record and then indexDocs array is build and in foreach loop it gets indexed. I think there is need to add a hook so that more documents can be added for that one record if needed. what you think about it?

**Comment by rengaw83** [comment]
Hi,
there is no need for a hook.

A record is passed to one or more indexers.
A indexer can only create one unique document. The unique id for the document is build by the contenttype and the record uid. 
A indexer only can representate one contenttype, not more. 

However you can register another indexer with a special contenttype. So you can create a document for the same record with different data.

Hope it helps.

**Comment by dextar1** [comment]
Thanks
