### ISSUE TITLE
Maybe add an optimised module icon

### ISSUE THREAD

**Issue by motordigital** [DMKEBUSINESSGMBH/typo3-mksearch#32]
The currently used png is a little small:
<img width="359" alt="bildschirmfoto 2017-07-04 um 09 41 10" src="https://user-images.githubusercontent.com/2326534/27820001-f506a4a6-609c-11e7-82af-1385245293ee.png">

Maybe use a svg file like that:
[module-mksearch.svg.zip](https://github.com/DMKEBUSINESSGMBH/typo3-mksearch/files/1121275/module-mksearch.svg.zip)

**Comment by Baachi** [comment]
Fixed via `409b285d0b39880d1c2d6b6890fe97fa11235992`
