### ISSUE TITLE
How one can index rendered page content in document?

### ISSUE THREAD

**Issue by dextar1** [DMKEBUSINESSGMBH/typo3-mksearch#33]
In Solr TYPO3 ext there is a field which is indexed named as content and in that field it fetches page content after rendering using a hook of tslib/class.tslib_fe.php which gives TypoScriptFrontendController and it gets content from that obj and then do some parsing etc then index that content. is there any possibility that mksearch is doing such kind of thing for elasticsearch or solr?

**Comment by hannesbochmann** [comment]
Of course there is the possibility but we didn't have time yet to implement it. At least for Solr searches there is a nice alternative called grouping. With that you can limit the search results to only one tt_content element per page. You can also raise the number of tt_content elements per page to have google-like search results.

Why do you need that?
