### ISSUE TITLE
How protected pages be indexed only for desired user groups?

### ISSUE THREAD

**Issue by dextar1** [DMKEBUSINESSGMBH/typo3-mksearch#34]
Hi,
If there is any possibility that pages having assigned some user groups can be indexed and upon searching if user is not logged in then doesnt show up and if user is logged in then they should show up in search result.

**Comment by dextar1** [comment]
ok there is a field which indexes fe_groups field with page record. but is there any way to filter search records based on that parameter without modifying any code?

**Comment by hannesbochmann** [comment]
mksearch does that out of the box for searches with Solr and Lucene. The support for ElasticSearch is not implemented in the moment.

In tx_mksearch_filter_SolrBase everything is handled [here](https://github.com/DMKEBUSINESSGMBH/typo3-mksearch/blob/master/filter/class.tx_mksearch_filter_SolrBase.php#L304). tx_mksearch_filter_ElasticSearchBase needs to be extended to do the same thing for ElasticSearch.
