### ISSUE TITLE
solrconfig.xml and shema.xml for SOLR 6.x

### ISSUE THREAD

**Issue by webfacer** [DMKEBUSINESSGMBH/typo3-mksearch#35]
Hi is there any pipeline where you suggest to update the SOLR xml´s?

**Comment by hannesbochmann** [comment]
No, not in the moment. What would you like to update?

**Comment by webfacer** [comment]
Nothing i would Like to typo3 mksearch with solr-6.5.1 version and need the
shema.xml and solrconfig.xml without that i cant create a testcore for
Apache Solr.

lg,

Davor

Am 13.09.2017 13:22 schrieb "Hannes Bochmann" <notifications@github.com>:

**Comment by hannesbochmann** [comment]
The schema.xml and solrconfig.xml shipped with mksearch are just examples. You can use whatever schema.xml and solrconfig.xml files you like. For example you could copy the shipped files, start a Solr core with those files and watch the Solr log for errors etc. Or you could check the changelog of Solr from version 6.3 to 6.5.1 to see what needs to be changed.

**Comment by webfacer** [comment]
Okey thank you for your help. I will try this now.

thanks

2017-09-13 13:45 GMT+02:00 Hannes Bochmann <notifications@github.com>:

**Comment by webfacer** [comment]
I have a last question because now the configs for Apache-Solr are just
"host, port and core" but what about user and password? do i just join it
or is there nothing planed like this?


2017-09-13 14:40 GMT+02:00 Davor Ilic <webfacer@gmail.com>:

**Comment by webfacer** [comment]
Also another question do you have a channel on slack/typo3?


2017-09-13 16:35 GMT+02:00 Davor Ilic <webfacer@gmail.com>:

**Comment by webfacer** [comment]
Oh man if you have time could you tell me why this error pops up? did i
missconfigured something or is this not compatible with typo3 7.6.x? The
errors pops up on "Admin Panel" and "Indexing Queue" Tab.

2017-09-13 16:40 GMT+02:00 Davor Ilic <webfacer@gmail.com>:

**Comment by hannesbochmann** [comment]
Authentication is not supported in the moment. A possible approach would be to restrict the access to Solr by IP.
No, we don't have a slack channel right now.
Please open a new issue with more information about the error. A screenshot, stack trace etc. would be helpful, too.
