### ISSUE TITLE
Filter Query

### ISSUE THREAD

**Issue by ThePinkOne** [DMKEBUSINESSGMBH/typo3-mksearch#37]
I've inserted the search plugin of mksearch and when I leave the input field empty I get - expectedly - everything what's in the core.
But when I actually try to search with a special keyword I get nothing, though I know there has to be result. So enabled the debug mode and that's what I see

```
array(4 items)
   Exception => 'Exception caught from Solr:'400' Status: Bad Request' (52 chars)
   fields => array(1 item)
   options => array(4 items)
      limit => 0 (integer)
      fq => '(-fe_group_mi:[* TO *] AND id:[* TO *]) OR fe_group_mi:0' (56 chars)
      debug => 1 (integer)
      facet => 'false' (5 chars)
   URL => 'http://localhost:8983/solr/shelltest/select?limit=0&fq=%28-fe_group_mi%3A%5B
      %2A+TO+%2A%5D+AND+id%3A%5B%2A+TO+%2A%5D%29+OR+fe_group_mi%3A0&debug=1&facet=
      false&wt=json&json.nl=map&q=contentType%3A%2A+AND+text%3A%28%22application%2
      2%29&start=0&rows=0' (247 chars)
```
There are two things I've noticed:
The searchURL looks different when I try to search in the Solr-Admin-Panel. It looks like this and I get the results I need

`http://localhost:8983/solr/shelltest/select?indent=on&q=*application*&wt=json`

The second thing is the filter query in the link above 
 `fq => '(-fe_group_mi:[* TO *] AND id:[* TO *]) OR fe_group_mi:0' (56 chars)`
Where does this fe_group_mi-thing come from? I can't remember that I've defined a filter query.

I think the filter query causes the problem, but I don't know where to disable it and where it is filled with this fe_group-thing.

I'm using the latest release of mksearch.

**Comment by hannesbochmann** [comment]
Is more information shown if you open the URL shown in the debug mode directly?
Have you used the shipped example schema.xml and solrconfig.xml as starting point? 
Furthermore it looks like your request handler is dismax but mksearch is configured to use the standard query parser. (you can see that in the q parameter)

The field fe_group_mi is added dynamically during indexing with mksearch. You don't have to worry about that filter query and it's certainly not the problem (but you can try - open the URL shown in the debug mode and remove the fq parameter). It makes sure that documents that have a fe_group restriction are not found by unauthorized users.

**Comment by ThePinkOne** [comment]
That's what I can see when I open the URL

`{"responseHeader":{"status":400,"QTime":12,"params":{"q":"contentType:* AND text:(\"application\")","debug":"1","json.nl":"map","limit":"0","start":"0","fq":"(-fe_group_mi:[* TO *] AND id:[* TO *]) OR fe_group_mi:0","rows":"0","facet":"false","wt":"json"}},"error":{"metadata":{"error-class":"org.apache.solr.common.SolrException","root-error-class":"org.apache.solr.common.SolrException"},"msg":"undefined field text","code":400}}`

I use the shipped schema.xml, but I have to use another solrconfig.xml. I use Solr 6 it is not ale to load the shipped one. I thought I can use any schema.xml and solrconfig.xml?
And I don't use Dismax, I chose default to be on the safe side for testing ;)
I attached some files for you - maybe they'll help a little bit.

![screenshot_mksearch](https://user-images.githubusercontent.com/32168086/31326822-e7ed7518-acca-11e7-9be3-edabfac74a58.png)
[solrconfig.txt](https://github.com/DMKEBUSINESSGMBH/typo3-mksearch/files/1367623/solrconfig.txt)
[schema.txt](https://github.com/DMKEBUSINESSGMBH/typo3-mksearch/files/1367622/schema.txt)

**Comment by hannesbochmann** [comment]
The message is pretty clear:
"msg":"undefined field text"

You have several options:
1.Recommended: Configure mksearch to use dismax either in the plugin or via TypoScript (you need to provide a suitable request handler in the solrconfig.xml, the default one would be sitesearch_german in EXT:mksearch/Configuration/Solr/conf6x/solrconfig.xml)
2. Define the field "text" in your schema.xml or replace "full_text_german" with "text", which can conflict with the fieldType "text"
3. Change the TypoScript Configuration to search in the default field "full_text_german" (lib.mksearch.defaultsolrfilter.params.mksearch.term-wrap = AND full_text_german:|)

**Comment by hannesbochmann** [comment]
The default schema.xml and solrconfig.xml are optimized for use with dismax. The default configuration uses the field "text", which is outdated. But we can't change that to keep backwards compatibility. 
I updated the documentation to make clear what needs to be changed when using the default query parser with the default schema.xml

**Comment by ThePinkOne** [comment]
Thank you for your quick reply. I tried the recommended way:

1. Chose DisMax as filter in the plugin (Search view for Solr)
2. Added the request handler sitesearch_german from the shipped solrconfig.xml to my solrconfig (see above) - I just copied and pasted the part.
3. Added sitesearch_german as Request Handler in Search view for Solr

...and it works :) thank you a lot
