### ISSUE TITLE
Incompatibility with MariaDB

### ISSUE THREAD

**Issue by motordigital** [DMKEBUSINESSGMBH/typo3-mksearch#38]
Unfortunately Debian decided against Oracle MySQL, why using MariaDB is crucial in some contexts.

The index configuration fails with errors on OP_EQ_INT syntax:

SQL QUERY IS NOT VALID
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'OP_EQ_INT 60  AND (`tx_mksearch_indices`.`deleted` = 0) AND (`tx_mksearch_indice' ...

SELECT count(DISTINCT tx_mksearch_indices.uid) as cnt FROM tx_mksearch_indices WHERE 1=1 AND tx_mksearch_indices.pid OP_EQ_INT 60  AND (`tx_mksearch_indices`.`deleted` = 0) AND (`tx_mksearch_indices`.`hidden` = 0)

**Comment by hannesbochmann** [comment]
OP_EQ_INT is a constant which seems to be not loaded and therefore is not replaced correct. @see #36 
Please update rn_base to version 1.5.0. It's only available through [github](https://github.com/digedag/rn_base).

**Comment by motordigital** [comment]
I am sorry. Yes, the reason for this problem was a not proper loaded rn_base. Within a comoposer setup we had to add a 

  "require": {
    "ruflin/elastica": "*"
  },

besides the mksearch itself.
