### ISSUE TITLE
Usage of external Solr index

### ISSUE THREAD

**Issue by AppWerft** [DMKEBUSINESSGMBH/typo3-mksearch#40]
Hi,
how it is possible to link an external Solr index? This index is independing of content of TYPO3 page.
Any ideas?

**Comment by hannesbochmann** [comment]
You can create the index as usually in mksearch. No need to bind any indexers to the index. This way the index can be used in any search plugin without getting content of TYPO3 indexed.
Of course the external index needs to be accessible via a URL.

**Comment by AppWerft** [comment]
Thanks for the quick answer. This helps me a lot.
