### ISSUE TITLE
ElasticSearch: Request body is required

### ISSUE THREAD

**Issue by jdinse** [DMKEBUSINESSGMBH/typo3-mksearch#43]
I'm trying to configure mksearch with ElasticSearch on TYPO3 8.7. As I'm trying to establish an index with `website;localhost,9200,/;` I'm getting an error with status 400 an the message _request body is required_.

By investigating the outgoing requests, I can see the following URLs:

    http://localhost:9200//website
    http://localhost:9200//website/
    http://localhost:9200//website/_open

it looks like the path `/` is wrong evaluated. If I leave the path empty, I get the message _No endpoint or operation is available_. The outgoing requests were these:

    http://localhost:9200/website
    http://localhost:9200/website/_open
    http://localhost:9200/_status

So does anybody know what's wrong here?

I'm working with the branch `elasticsearch-elastica-update `.

**Comment by hannesbochmann** [comment]
Could you please try with the master? elasticsearch-elastica-update is no usable branch. The master should work with ElasticSearch 5.x
