### ISSUE TITLE
Support for TYPO3 9.5 LTS

### ISSUE THREAD

**Issue by ameos** [DMKEBUSINESSGMBH/typo3-mksearch#45]
Hello,

Have you plannified a support of TYPO3 9.5LTS ?

Thanks for your work.

Regards,
Stéphane

**Comment by hannesbochmann** [comment]
Yes, we're working on it. But there's no definite time when we will be finished.

**Comment by Baachi** [comment]
Duplicate with Issue #46. I'll close here, we track the status in the linked ticket.
