### ISSUE TITLE
Fatal error in indexerBase_postProcessSearchData hook

### ISSUE THREAD

**Issue by digedag** [DMKEBUSINESSGMBH/typo3-mksearch#48]
I have an NPE in a indexerBase_postProcessSearchData hook, because IndexerDocument is `null`. This is because an indexer can return `null` in method `indexData()`. [Link](https://github.com/DMKEBUSINESSGMBH/typo3-mksearch/blob/6c1e5f6a36dc84157a5b3c66e5db40743ef38ac4/indexer/class.tx_mksearch_indexer_Base.php#L166) This is allowed [by documention](https://github.com/DMKEBUSINESSGMBH/typo3-mksearch/blob/6c1e5f6a36dc84157a5b3c66e5db40743ef38ac4/indexer/class.tx_mksearch_indexer_Base.php#L879).
So if the indexer returns `null` it makes no sense to process any additional code. The final hook should not be called.

**Comment by rengaw83** [comment]
I think in this case the documentation was wrong.
The `indexData` method should only be called, if there is realy an indexing and a indexer document.   

The `return null` means: "ignore this queue entry, there is nothing to be indexed". 
This can/should be handled in the `stopIndexing`, `isIndexableRecord` or `hasDocToBeDeleted` steps before.
