### ISSUE TITLE
<add> tag is filled with deprecated attributes

### ISSUE THREAD

**Issue by darthnorman** [DMKEBUSINESSGMBH/typo3-mksearch#58]
When using mksearch with Solr 4 or higher, log is filled with warnings:
https://i.imgur.com/GDFPb61.png

The <add> tag is filled with deprecated attributes. It is recommended to replace these with the "overwrite" attribute:
https://cwiki.apache.org/confluence/display/solr/UpdateXmlMessages#UpdateXmlMessages-Optionalattributesfor%22add%22

**Comment by hannesbochmann** [comment]
The Apache PHP Solr library which we use to communicate with Solr is responsible for those old attributes. I'm afraid this library is outdated. At least I didn't find a current version. To be honest I don't even know what version we're using exactly. So I see 3 options:

- fix those problems in the library by ourselves
- look a bit more around and try to find a more current version of the library
- switch to another library

The third option is a big task so I don't see that in the near future.

**Comment by hannesbochmann** [comment]
This [version](https://github.com/reprovinci/solr-php-client) seems to be more recent. I will try it when I have time.
