### ISSUE TITLE
Improve scheduler performance

### ISSUE THREAD

**Issue by darthnorman** [DMKEBUSINESSGMBH/typo3-mksearch#59]
On big sites where root pages are often changed or sites with lots of imports the scheduler takes more time on queueing items that it does on indexing them. Sometimes the scheduler never indexes anything and breaks or runs into a timeout while trying to queue new or changed items.

Is there a better way to queue and index than to do both in one scheduler task? 
Can we split those actions into separate tasks?

**Comment by hannesbochmann** [comment]
There need to be 2 things done:

- [ ] make the scheduler able to run in parallel
- [ ] don't trigger an optimize for each commit to a solr core

**Comment by hannesbochmann** [comment]
The scheduler now runs automatically in parallel and the optimize is omitted. This way queue entries should be indexed much faster. The downside is of course a higher load on the server and solr as several indexing tasks might run in parallel.
