### ISSUE TITLE
Frontend error Typo3 9.5 PHP 7.3

### ISSUE THREAD

**Issue by p-view** [DMKEBUSINESSGMBH/typo3-mksearch#67]
Argument 1 passed to tx_mksearch_util_Filter::getPageLimit() must implement interface tx_rnbase_IParameters, instance of Sys25\RnBase\Frontend\Request\Parameters given, called in /html/typo3/typo3conf/ext/mksearch/filter/class.tx_mksearch_filter_SolrBase.php on line 191

Force search =1

**Comment by rengaw83** [comment]
In Version 9.5.7 we has to switch the Interface after a breaking change in rn_base in [v1.11](https://github.com/digedag/rn_base/releases/tag/v1.11.0).

Which Version of rn_base do you use? Can you upgrade rn_base to the latest version .

**Comment by p-view** [comment]
i use rn_base 1.11.1 (latest), Typo3 9.5.14 and mksearch 9.5.2
Should i downgrade something?

**Comment by rengaw83** [comment]
You can downgrade rn_base to 1.10.* or upgrade mksearch to at least  9.5.7.

**Comment by p-view** [comment]
Thanks, thats helped.
