### ISSUE TITLE
ElasticSearch plugin doesn't work, needs tx_rnbase_IParameters

### ISSUE THREAD

**Issue by dzschille** [DMKEBUSINESSGMBH/typo3-mksearch#69]
i just installed mksearch and i am getting this error on the page with the search plugin:

`Argument 1 passed to tx_mksearch_action_ElasticSearch::handlePageBrowser() must be an instance of tx_rnbase_parameters, instance of Sys25\RnBase\Frontend\Request\Parameters given, called in /var/www/public/typo3conf/ext/mksearch/action/class.tx_mksearch_action_ElasticSearch.php on line 69`

TYPO3: 9.5.14
mksearch: latest master
rn-basern-base: v1.11.2

Some idea what could be wrong? Is it my setup or has it to do with the current replacement of the tx_rnbase_IParameters?

**Comment by kombinatgmbh** [comment]
Danke, @rengaw83 , funktioniert jetzt!
