### ISSUE TITLE
Question: which target to choose for PRs?

### ISSUE THREAD

**Issue by kombinatgmbh** [DMKEBUSINESSGMBH/typo3-mksearch#81]
When i want to make a PR with some improvements, which branch should i use to fork from and later choose as target of my PR? I see master is behind the 10.x and 11.x. Just the 10.x which is the default?

**Comment by hannesbochmann** [comment]
In the moment the 10.x branch is still the default. But in some weeks 11.x will become the default branch. So it's better to base your fork on the 11.x branch.

**Comment by kombinatgmbh** [comment]
Thanks for the quick clarification!
