### ISSUE TITLE
Compatibility with TYPO3 v10.4.x broken

### ISSUE THREAD

**Issue by neufeind** [DMKEBUSINESSGMBH/typo3-mksearch#84]
ext_emconf claims compatibility to 10.4.25. But that's not the case. It seems not even a composer-based installation of 10.4.x (which pulls in a newer fluid-version due to the deps) would work.
Do you have it running on 10.4.x-installations? If really broken, should we maybe consider fixing the current major-release and do another which is v11 upward only?

**Comment by neufeind** [comment]
Call to undefined method TYPO3\CMS\Fluid\Core\Rendering\RenderingContext::getRequest()
in /var/www/html/typo3conf/ext/mksearch/Classes/ViewHelpers/Format/HtmlViewHelper.php line 49

     */
    public static function renderStatic(array $arguments, \Closure $renderChildrenClosure, \TYPO3Fluid\Fluid\Core\Rendering\RenderingContextInterface $renderingContext)
    {
        $parseFuncTSPath = $arguments['parseFuncTSPath'];
        $request = $renderingContext->getRequest();
        $isBackendRequest = $request->getAttribute('applicationType')
            && ApplicationType::fromRequest($request)->isBackend();
        if ($isBackendRequest) {
            static::simulateFrontendEnvironment();

Seems related to this patch which is not present in TYPO3 v10.4.x:
https://github.com/TYPO3/typo3/commit/068351eaf00ed427b9e7035f27a77cba30f4e001

**Comment by neufeind** [comment]
executeQuery() and executeStatement()
Changed in version 11.5: The widely used ->execute() method has been split into executeQuery() and executeStatement(). executeQuery() returns a \Doctrine\DBAL\Result instead of a \Doctrine\DBAL\Statement. executeStatement() returns the number of affected rows. The ->execute() method has been removed with TYPO3 v13.0.
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Database/QueryBuilder/Index.html#executequery-and-executestatement

mksearch/util/class.tx_mksearch_util_UserGroups.php already uses executeQuery() which makes it requiring at least TYPO3 v11.5

**Comment by hannesbochmann** [comment]
Hi, we're using mksearch in several 10.4 and 11.5 projects. But we use the 10.4 branch with TYPO3 10.4. So I guess the 11.5 branch indeed has no compatibility to TYPO3 10.4 even though we state that. I'm sorry for that trouble. We need to discuss what we gonna do about that. Either we fix the compatibility in the 11.5 branch or we drop the compatibility for TYPO3 10.4 in the 11.5 branch. For the time being please use mksearch 10.x versions. There should be no real difference to 11.x except for the compatibility to TYPO3 versions.

**Comment by hannesbochmann** [comment]
I fixed the mentioned problems and released version 11.0.13 which hopefully is now working with TYPO3 10.4 in all places. At least for me it did and I found no further problems.
